language: java

before_install:
  - wget http://apache.claz.org/maven/maven-3/3.3.9/binaries/apache-maven-3.3.9-bin.tar.gz
  - tar zxvf apache-maven-3.3.9-bin.tar.gz
  - chmod +x apache-maven-3.3.9/bin/mvn
  - export M2_HOME=$PWD/apache-maven-3.3.9
  - export PATH=$PWD/apache-maven-3.3.9/bin:${PATH}
  - hash -r

jdk:
  - oraclejdk8

script: mvn -v && cd DSML/src/xtext/edu.vanderbilt.isis.chariot.mvn && mvn clean install

notifications:
  email: false
